// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package database

import (
	"time"

	"github.com/google/uuid"
)

type Task struct {
	ID          uuid.UUID
	Description string
	IsCompleted bool
	CreatedAt   time.Time
	DueDate     time.Time
}
